### PR TITLE
force evaluate animation system, fix #10

### LINKED ISSUE #10: Keyframes are not applied to sequences in background and "Lock interface" modes

### PR DESCRIPTION
**Pull request by losanc**

### CODE REVIEW

**Comment by digitalillusions** [comment]
This looks good, but is it really necessary to set the rotation in this way? Seems like its a bit redundant to set quaternion, euler AND axis angle, no?

**Comment by losanc** [comment]
because blender only use object with one rotation mode, (in `obj.rotation_mode` setting). Then for example, if the object is set to `rotation_quaterion`, then you insert the key frames with rotation. Now you should be able to play the animation, but if you change the animation mode to `rotation_euler`, (without changing anything else with keyframes) the animation system won't work, unless you switch back to `rotation_quaternion`.
So, it feels like it's 3 independent system to rotate the object.

Also, for example, if I only update `rotation_quaterion` in the code, but the animation is set to rotate with `rotation_euler`, then `rotation_euler` is actually not updated, then blender won't rotate the object

**Comment by digitalillusions** [comment]
wouldnt the cleaner solution then be to only set the correct rotation based on rotation mode?

**Comment by losanc** [comment]
do you mean something like this?
```python
if obj.rotation_mode == "EULER":
    obj.rotation_euler = obj.evaluated_get(depsgraph).rotation_euler
if obj.rotation_mode == "QUATERNION":
    obj.rotation_quaternion = obj.evaluated_get(depsgraph).rotation_quaternion
if obj.rotation_mode == "AXIS_ANGLE":
    obj.rotatino_axis = obj.evaluated_get(depsgraph).rotation_axis
```

**Comment by digitalillusions** [comment]
yes, but make it an `elif`. you could even use the `match case` syntax introduced in python 3.10.

**Comment by losanc** [comment]
ok. will do it later

**Comment by digitalillusions** [comment]
thanks, i will merge this as it is for now but will probably make some adjustments later

**Pull request merged**
